title: N-hat 

# Authors documented under _data

# google-ID: 'UA-80213386-1'

menu:
- {name: 'About', url: '../about'}
- {name: 'Projects', url: '../projects'}

social:
- {icon: 'github', link: 'https://www.github.com/nhatbui'}
- {icon: 'twitter', link: 'https://twitter.com/gnatbuoy'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/nhatqbui/'}
- {icon: 'envelope', link: 'mailto:nhat@nhatqbui.com'}
- {icon: 'rss-square', link: 'https://www.github.com/nhatbui/feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
